# Generated by Django 4.2.7 on 2023-11-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='content',
            field=models.TextField(verbose_name='Primary_text'),
        ),
    ]
