# Generated by Django 4.2.7 on 2023-11-22 15:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_pages_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='created_data',
            field=models.DateField(auto_created=True, default=django.utils.timezone.now),
        ),
    ]
