# Generated by Django 4.2.7 on 2023-11-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_pages_created_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseHtml',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/img/basic', verbose_name='Image')),
                ('about', models.CharField(max_length=100, verbose_name='About')),
            ],
            options={
                'verbose_name': 'base.html Image',
                'verbose_name_plural': 'base.html Images',
                'ordering': ['image'],
            },
        ),
    ]
