# Generated by Django 4.2.7 on 2023-11-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_basehtml'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseHtml',
        ),
        migrations.AddField(
            model_name='pages',
            name='href_name',
            field=models.CharField(max_length=50, null=True, verbose_name='link'),
        ),
    ]
