# Generated by Django 4.2.7 on 2023-11-26 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_api_filters'),
    ]

    operations = [
        migrations.DeleteModel(
            name='API_filters',
        ),
    ]
